- name: run common tasks
  include_tasks: task_common

- name: install k8s-network
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=$master_ip --kubernetes-version=v1.10.5

- name: get token
  shell: kubeadm token list | tail -n 1 | awk '{print $1;}'
  register: kubeadm_token

- name: install pod network
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f ../flannel.yml


- name: change pod-eviction time
  replace:
    insertafter: '\s+- kube-controller-manager'
    line: '    - --pod-eviction-timeout=2s'

