- name: reset previous cluster
  shell: kubeadm reset
  become: yes
  become_user: root

- name: start new cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=131.131.131.100 --kubernetes-version=v1.10.5
  become: yes
  become_user: root

- name: copy admin conf file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  become: yes
  become_user: root

- name: copy flannel file
  copy:
    src: ../files/flannel.yml
    dest: /root/
    remote_src: no
  become: yes
  become_user: root

- name: start flannel network
  shell: kubectl apply -f /root/flannel.yml
  become: yes
  become_user: root

- name: remove flannel file
  file:
    path: /root/flannel.yml
    state: absent
