- name: disable swap
  shell: swapoff -a
  become: yes
  become_user: root

- name: edit fstab
  replace:
    path: /etc/fstab
    regexp: '^/dev/mapper/centos-swap'
    replace: '#/dev/mapper/centos-swap' 
  become: yes
  become_user: root

- name: install kubeadm
  yum:
    name: '{{ item }}'
    state: present
    disablerepo: '*'
    enablerepo: localrepo
  become: yes
  become_user: root
  register: REGISTER_KUBEADM
  with_items:
  - kubeadm
  - cri-tools

- name: restart kubelet service
  service:
    name: kubelet
    state: restarted
  when: REGISTER_KUBEADM.changed
  become: yes
  become_user: root

- name: enabled kubelet service
  service:
    name: kubelet
    enabled: yes
  become: yes
  become_user: root

- name: disable seLinux
  selinux:
    state: disabled
  become: yes
  become_user: root

- name: modify sysctl
  sysctl:
    name: '{{ item }}'
    value: 1
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables 
  register: REGISTER_IPTABLES
  become: yes
  become_user: root

- name: sysctl update
  command: sysctl --system
  when: REGISTER_IPTABLES.changed
  become: yes
  become_user: root

- name: modify k8s driver
  replace:
    regexp: cgroup-driver=systemd
    replace: cgroup-driver=cgroupfs
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  become: yes
  become_user: root

- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  become: yes
  become_user: root

- name: pull docker images
  docker_image:
    name: '{{ DOCKER.REGISTRY.IP }}/{{ item }}'
    state: present
  with_items: '{{ K8s.MASTER.IMAGES }}'
  register: REGISTER_DOCKER_IMAGES_PULLED
  become: yes
  become_user: root

- name: tag docker images
  docker_image:
    name: '{{ DOCKER.REGISTRY.IP }}/{{ item }}'
    state: present
    repository: '{{ K8s.MASTER.REPOSITORY }}/{{ item }}'
    pull: no
    push: no
  with_items: '{{ K8s.MASTER.IMAGES }}'
  register: REGISTER_DOCKER_IMAGES_PULLED
  become: yes
  become_user: root

