- name: update yum repo
  shell: yum clean all
  become: yes
  become_user: root

- name: install kubeadm
  yum:
    name: kubeadm
    state: present
    disablerepo: '*'
    enablerepo: localrepo
  become: yes
  become_user: root

- name: disable seLinux
  selinux:
    state: disabled
  become: yes
  become_user: root

- name: modify sysctl
  sysctl:
    name: '{{ item }}'
    value: 1
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables 
  become: yes
  become_user: root

- name: modify k8s driver
  replace:
    regexp: cgroup-driver=systemd
    replace: cgroup-driver=cgroupfs
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  become: yes
  become_user: root

- name: sysctl update
  command: sysctl --system
  become: yes
  become_user: root

- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
