- name: create pip config folder
  file:
    path: '{{ PIP.REPO.CONF.PATH }}'
    state: directory
  become: yes
  become_user: root

- name: pip configuration
  template:
    dest: '{{ PIP.REPO.CONF.PATH }}/pip.conf'
    src: '{{ PIP.REPO.CONF.TEMPLATE }}'
  become: yes
  become_user: root

- name: copy files to pip repo
  copy:
    src: '{{ role_path }}/files/'
    dest: /root/pip_repo/
  become: yes
  become_user: root
