- name: install httpd
  yum:
    name: httpd
    update_cache: no
    disablerepo: '*'
    enablerepo: localrepo
  register: httpd_installed
  become: yes
  become_user: root

- name: conf httpd
  template:
    src: '{{ role_path }}/templates/template_httpd_conf.j2'
    dest: /etc/httpd/conf.d/vhost.conf
  register: httpd_conf
  become: yes
  become_user: root

- name: copy files to pip repo
  copy:
    src: '{{ role_path }}/files/'
    dest: /var/www/html/example.com/
  register: httpd_new_files
  become: yes
  become_user: root

- name: enable httpd
  systemd:
    name: httpd
    enabled: yes
  become: yes
  become_user: root

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
  when: 'httpd_installed.changed or httpd_conf.changed or httpd_new_files.changed'
  become: yes
  become_user: root

- name: open port 80
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  register: port_opened
  become: yes
  become_user: root

- name: open http service
  firewalld:
    service: http
    permanent: yes
    state: enabled
  register: service_opened
  become: yes
  become_user: root

- name: restart firewall
  systemd:
    name: firewalld
    state: restarted
  when: 'port_opened.changed or service_opened.changed'
  become: yes
  become_user: root
