- name: create pip config folder
  file:
    path: '{{ PIP.REPO.CONF.PATH }}'
    state: directory
  become: no

- name: pip configuration
  template:
    dest: '{{ PIP.REPO.CONF.PATH }}'/pip.conf
    src: '{{ PIP.REPO.CONF.TEMPLATE }}'
  become: no
