all:
  hosts:
    local:
      ansible_host: localhost
    admin:
      ansible_host: 131.131.131.201
  children:
    k8s:
      hosts:
        master:
          ansible_host: 131.131.131.100
          ansible_network_os: centos
          ismaster: true
      children:
        nodes:
          hosts:
            node1:
              ansible_host: 131.131.131.101
              ansible_network_os: centos
            node2:
              ansible_host: 131.131.131.102
              ansible_network_os: centos
            node3:
              ansible_host: 131.131.131.103
              ansible_network_os: centos
