- name: install yum-utils
  yum:
    name: '{{ YUM_LOCAL_REPO_SRC }}/{{ ITEM }}'
  with_items:
    - '{{ RPM_YUM_UTILS_LIST }}'
  become: yes

- name: update yum-repolist
  template:
    dest: '{{ YUM_LOCAL_REPO_CONFIG_PATH }}'
    src: '{{ YUM_LOCAL_REPO_CONFIG_TEMPLATE }}'
  become: yes

- name: install ftp server
  yum:
    name: '{{ YUM_LOCAL_REPO_SRC }}/{{ RPM_VSFTPD }}'
    state: present
  become: yes

- name: start ftp server
  systemd:
    name: vsftpd
    state: started
    enabled: yes
  become: yes

- name: copy localrepo files to ftp folder
  copy:
    src: '{{ YUM_LOCAL_REPO_SRC }}'
    dest: '{{ YUM_LOCAL_REPO_FTP_FOLDER }}'
    directory_mode: yes
  owner: root
  group: root
  mode: 0744
  become: yes

- name: create repo
  shell:
    chdir: '{{ YUM_LOCAL_REPO_FTP_FOLDER }}'
    cmd: createrepo .
  become: yes

- name: open port 21 for ftp
  firewalld:
    port: 21/tcp
    permanent: true
    state: enabled
  become: yes
