- name: Install yum-utils
  yum:
    name: "{{ LOCALREPO_SRC }}/{{ item }}"
  with_items:
    - libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm
    - python-deltarpm-3.6-3.el7.x86_64.rpm
    - deltarpm-3.6-3.el7.x86_64.rpm
    - python-deltarpm-3.6-3.el7.x86_64.rpm
    - createrepo-0.9.9-28.el7.noarch.rpm
- name: add repo metadata to /etc
  blockinfile:
    path: /etc/yum.repos.d/localrepo.repo
    state: present
    create: yes
    marker: ""
    content: |
      [localrepo]
      name=Hotscan Repository
      baseurl=ftp://{{ LOCALREPO_FTP_URL }}/pub
      gpgcheck=0
      enabled=1
- name: install ftp server
  yum:
    name: "{{ LOCALREPO_SRC }}/vsftpd-3.0.2-22.el7.x86_64.rpm"
    state: present
- name: start ftp server
  systemd:
    name: vsftpd
    state: started
    enabled: yes
- name: copy localrepo to ftp folder
  copy:
    src: "{{ LOCALREPO_SRC }}"
    dest: /var/ftp/pub
    directory_mode: yes
- name: createrepo
  shell:
    chdir: /var/ftp/pub
    cmd: createrepo .
- name: open port 21 for ftp
  firewalld:
    port: 21/tcp
    permanent: true
    state: enabled
