- name: Install necessary libraries and utilitites
  yum:
    name: "{{ item }}"
    update_cache: no
    disablerepo: "*"
    enablerepo: localrepo
  with_items:
    - epel-release
    - python-setuptools
    - python-pip
- name: create .pip folder
  file:
    path: "{{ WORKING_DIR }}/.pip"
    state: directory
- name: pip configuration
  blockinfile:
    path: "{{ WORKING_DIR }}/.pip/pip.conf"
    create: yes
    marker: ""
    content: |
      [global]
      index-url = {{ PIP_LOCATION }}
- name: Install docker-py
  pip:
    name: docker-py
    editable: yes
- name: docker pull image
  docker_image:
    name: registry
    tag: 2	
    load_path: {{ DOCKER_HUB_LOCATION }}/registry.tar
- name: docker run
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
     - "5000:5000"
