
- name: install ntp
  yum:
    name: ntp
    state: present
    disablerepo: '*'
    enablerepo: localrepo
  become: yes
  become_user: root

- name: configure ntp
  template:
    src: '{{ role_path }}/files/ntp-client.conf'
    dest: /etc/ntp.conf
    backup: yes
  become: yes
  become_user: root

- name: stop ntp service
  systemd:
    name: ntpd
    state: stopped
  become: yes
  become_user: root

- name: update ntp time
  shell: ntpdate admin 
  become: yes
  become_user: root

- name: start ntp service
  systemd:
    name: ntpd
    enabled: yes
    state: started
  become: yes
  become_user: root
