#! /bin/bash

# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# [CGI Hotscan] Kubernetes-installion (MASTER)
#               Description:
#
#          This script is written to install Kubernete master For the cluster
#          in ubuntu Debian HyperOs system       
#          
#	   For the script to run without fail you should have internet connection 	
# Dependency:
#           https://download.docker.com
#	    https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------

#-------------------------------------------
# ------------------------------------------
# Style tag declaration

r=`tput setaf 1`
g=`tput setaf 2`
re=`tput sgr0`
b=`tput bold`

echo ${re}
# Kubernetes Version 

k8s_version="v1.10"


#-------------------------------------------
#-------------------------------------------



echo -e "Dashbaord Setup Started ..... "

kubectl taint nodes $(hostname) key:NoSchedule- &> /dev/null
kubectl taint nodes $(hostname) node-role.kubernetes.io/master:NoSchedule- &> /dev/null

kubectl create -f heapster/deploy/kube-config/influxdb/influxdb.yaml
kubectl create -f heapster/deploy/kube-config/influxdb/heapster.yaml
kubectl create -f heapster/deploy/kube-config/influxdb/grafana.yaml

kubectl create -f heapster/deploy/kube-config/rbac/heapster-rbac.yaml

# creating Dashboard

sleep 1m

chmod 777 dashboard-creation.yml
kubectl create -f dashboard-creation.yml || { echo "dashboard creation failed"; exit 1; }

# admin rights 
chmod 777 dashboard-admin.yaml
kubectl create -f dashboard-admin.yaml

echo -e "\nDashboard is Up and Running to access the dashboard run ${b}'kubectl proxy'${re}(preferably in some other terminal)\n  "

echo -e "${b}Dashboard will be available at:${re} http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/."

kubectl taint nodes $(hostname) key=value:NoSchedule &> /dev/null

