- name: install squid
  yum:
    name: '{{ item }}'
    update_cache: no
    disablerepo: '*'
    enablerepo: '{{ YUM_LOCAL_REPO.CONFIG.ID }}'
  with_items:
    - '{{ SQUID.YUM_DEPENDENCY }}'
  become: yes
  become_user: root

- name: create passwdfile for squid proxy
  htpasswd:
    path: '{{ SQUID.PASSWD.PATH }}'
    name: '{{ SQUID.USER }}'
    password: '{{ SQUID.PASSWORD }}'
    crypt_scheme: '{{ SQUID.PASSWD.HASH_SCHEME }}'
    owner: root
    group: root
    mode: 0604
  become: yes
  become_user: root

- name: open squid port in firewalld
  firewalld:
    port: '{{ SQUID.PORT }}/tcp'
    zone: public
    permanent: true
    state: enabled
  become: yes
  become_user: root

- name: restart firewall service
  systemd:
    name: firewalld
    state: restarted
  become: yes
  become_user: root

- name: edit squid conf file - add ip range
  replace:
    path: '{{ SQUID.CONF_PATH }}'
    regexp: '192\.168\.0\.0/16'
    replace: '{{ SQUID.IP_RANGE }}'
  become: yes
  become_user: root

- name: edit squid conf file - add squid port
  replace:
    path: '{{ SQUID.CONF_PATH }}'
    regexp: '^http_port\s+3128'
    replace: 'http_port {{ SQUID.PORT }}'
  become: yes
  become_user: root

- name: edit squid conf file - add authentication
  blockinfile:
    path: '{{ SQUID.CONF_PATH }}'
    state: present
    marker: ''
    insertafter: 'acl CONNECT method CONNECT'
    content: |
      auth_param basic program /usr/lib64/squid/basic_ncsa_auth {{ SQUID.PASSWD.PATH }}
      auth_param basic realm proxy
      acl authenticated proxy_auth REQUIRED
      http_access allow authenticated
  become: yes
  become_user: root

- name: start squid service
  service:
    name: squid
    state: started
    enabled: yes
  become: yes
  become_user: root
