- name: install squid
  yum:
    name: "{{ item }}"
    update_cache: no
    disablerepo: "*"
    enablerepo: "{{ YUM_LOCAL_REPO_CONFIG_ID }}"
  with_items:
    - "{{ YUM_SQUID_DEPENDENCY_LIST }}"
  become: yes
  become_user: ansible

- name: create passwdfile for squid proxy
  htpasswd:
    path: "{{ SQUID_PASSWD_PATH }}"
    name: "{{ SQUID_USER }}"
    password: "{{ SQUID_PASSWORD }}"
    crypt_scheme: "{{ SQUID_PASSWORD_HASH_SCHEME }}"
    owner: root
    group: root
    mode: 0604
  become: yes
  become_user: ansible

- name: open squid port in firewalld
  firewalld:
    port: "{{ SQUID_PORT }}/tcp"
    zone: public
    permanent: true
    state: enabled
  become: yes
  become_user: ansible

- name: restart firewall service
  systemd:
    name: firewalld
    state: restarted
  become: yes
  become_user: ansible

- name: edit squid conf file - add ip range
  replace:
    path: "{{ SQUID_CONF_PATH }}"
    regexp: '192\.168\.0\.0/16'
    replace: '{{ SQUID_IP_RANGE }}'
  become: yes
  become_user: ansible

- name: edit squid conf file - add squid port
  replace:
    path: "{{ SQUID_CONF_PATH }}"
    regexp: '^http_port\s+3128'
    replace: 'http_port {{ SQUID_PORT }}'
  become: yes
  become_user: ansible

- name: edit squid conf file - add authentication
  blockinfile:
    path: "{{ SQUID_CONF_PATH }}"
    state: present
    marker: ""
    insertafter: 'acl CONNECT method CONNECT'
    content: |
      auth_param basic program /usr/lib64/squid/basic_ncsa_auth {{ SQUID_PASSWD_PATH }}
      auth_param basic realm proxy
      acl authenticated proxy_auth REQUIRED
      http_access allow authenticated
  become: yes
  become_user: ansible

- name: start squid service
  service:
    name: squid
    state: started
    enabled: yes
  become: yes
  become_user: ansible
