- name: install docker-ce
  yum:
    name: docker-ce
    update_cache: no
    disablerepo: '*'
    enablerepo: localrepo
  become: yes
  become_user: root
  notify:
  - restart docker

- name: restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
  become: yes
  become_user: root
