- name: docker pull registry image
  docker_image:
    name: registry
    tag: 2	
    load_path: '{{ role_path }}/files/{{ DOCKER.REGISTRY.IMAGE_TAR }}'
  become: yes
  become_user: root

- name: docker run registry image
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
     - '{{ DOCKER.REGISTRY.PORT_MAPPING }}'
  become: yes
  become_user: root
