- name: install docker-ce
  yum:
    name: docker-ce
    update_cache: no
    disablerepo: '*'
    enablerepo: localrepo
  register: docker_installed
  become: yes
  become_user: root

- name: restart docker
  service:
    name: docker
    state: restarted
  when: docker_installed.changed
  become: yes
  become_user: root

- name: enable docker
  service:
    name: docker
    enabled: yes
  become: yes
  become_user: root
