- name: install docker-ce
  yum:
    name: docker-ce
    update_cache: no
    disablerepo: '*'
    enablerepo: '{{ YUM_LOCAL_REPO.CONFIG.ID }}'
  become: yes
  become_user: ansible

- name: start docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
  become_user: ansible
