- name: install docker-ce
  yum:
    name: docker-ce
    update_cache: no
    disablerepo: '*'
    enablerepo: localrepo
  become: yes
  become_user: root

- name: start docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes
  become: yes
  become_user: root
