- name: install ansible-docker module dependencies
  yum:
    name: '{{ item }}'
    update_cache: no
    disablerepo: '*'
    enablerepo: '{{ YUM_LOCAL_REPO.CONFIG.ID }}'
  with_items:
    - '{{ DOCKER.IP_RANGE }}'
  become: yes
  become_user: ansible

- name: install docker-py
  pip:
    name: docker-py
    editable: yes
  become: no

- name: docker pull registry image
  docker_image:
    name: registry
    tag: 2	
    load_path: '{{ DOCKER.HUB_LOCATION }}/{{ DOCKER.IMAGE_REGISTRY_TAR }}'
  become: no

- name: docker run registry image
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    ports:
     - '{{ DOCKER.REGISTRY_PORT_MAPPING }}'
  become: no
