- name: add ip to inmemory inventory file
  add_host:
    hostname: '{{ NETWORK.TEMP_IP }}'
    groups: temp
    delegate_to: 127.0.0.1
  become: no

- name: convert dhcp to static
  template:
    dest: /etc/sysconfig/network-scripts/ifcfg-em1
    src: ../templates/template_staticip.j2
  become: yes
  become_user: root

- name: turn off networkmanager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no
  become: yes
  become_user: root

- name: restart server
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  become: yes
  become_user: root
