- hosts: admin
  connection: local
  gather_facts: no
  vars:
    yum:
      setup: true
    docker:
      registry: true
  roles:
    - role_yum
    - role_network
    - role_pip
    - role_ansible
    - role_docker
