- hosts: nodes
  remote_user: ansible
  connection: ssh
  gather_facts: no
  vars:
    docker:
      registry: false
    k8s:
      addnode: false
      node: true
      dashboard: false
      cluster_start: false
      reset: false
    yum:
      setup: false
  roles:
    - role_yum
    - role_network
    - role_docker
    - role_kubernetes
