- hosts: node3
  remote_user: ansible
  connection: ssh
  gather_facts: no
  vars:
    docker:
      registry: false
    k8s:
      addnode: false
      node: false
      start: false
      reset: true
    yum:
      setup: false
    pip:
      setup: false
  roles:
    - role_kubernetes
