- hosts: admin
  connection: ssh
  gather_facts: no
  vars:
    ibmmq:
      start: true
      install: false
      create: false
    oracle:
      shutdown: false
      startup: true
  roles:
  - role_oracle
  - role_ibmmq
