- hosts: node4
  remote_user: ansible
  connection: ssh
  gather_facts: no
  vars:
    docker:
      install: true
      insecure: true
      registry: false
      all: false
    network:
      hostname: true
      staticip: true
      all: true
    yum:
      config: true
      setup: false
      all: false
  roles:
    - role_yum
    - role_network
    - role_docker
