- name: add ip to inmemory inventory file
  add_host:
    hostname: 192.168.163.5
    groups: temp
    delegate_to: 127.0.0.1
- name: edit hostname
  shell: hostnamectl set-hostname "{{ HOSTNAME }}"
- name: convert dhcp to static
  replace:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ INTERFACE  }}"
    regexp: 'dhcp'
    replace: 'static'
- name: add ip addr
  blockinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ INTERFACE  }}"
    marker: ""
    insertafter: 'BOOTPROTO.*'
    content: |
      IPADDR="{{ IP_ADDR }}"
      NETMASK="{{ NETMASK }}"
      GATEWAY="{{ GATEWAY }}"
      DNS1="{{ DNS1 }}"
- name: turn on onboot
  replace:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ INTERFACE  }}"
    regexp: 'ONBOOT\s*=\s*"no"'
    replace: 'ONBOOT="yes"'
- name: turn off networkmanager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no
- name: restart server
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
