- name: install libraries (only for centos 7)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ RPM_IBMMQ_DEPENDENCY_LIST }}"
- name: install ibm rpm
  file:
    path: "{{ IBMMQ_WD }}"
    state: directory
- name: untar ibmmq src code
  unarchive:
    src: "{{ IBMMQ_SRC }}"
    dest: "{{ IBMMQ_WD }}"
- name: run ibm mq license
  shell: 
    cmd: echo "1" | ./mqlicense.sh --stdin && ./crtmqpkg mqmpkg
    chdir: "{{ IBMMQ_WD }}"
- name: install ibm rpm
  yum:
    name: "{{IBMMQ_WD}}/{{item}}"
    state: present
  with_items:
    - "{{ RPM_IBMMQ_LIST }}"
- name: run other commands
  shell: /opt/mqm/bin/setmqinst -i -p /opt/mqm/
- name: clean up
  shell:
    cmd: rm -rf *
    chdir: "{{ IBMMQ_WD }}"
