- name: install docker-ce
  yum:
    name: docker-ce
    update_cache: no
    disablerepo: "*"
    enablerepo: "{{ YUM_LOCAL_REPO_ID }}"
- name: start docker service
  systemd:
    name: docker
    state: started
    enabled: yes
