DOCKER:
  REGISTRY:
    IP: 192.168.163.201:5000

IBMMQ:
  QMGR:
    NAME: DOCKER
    CHANNEL: DOCKER_CHANNEL
    PORT: 30001
  QUEUE:
    1: HOTSCANINQ
    2: HOTSCANOUTQ1
    3: HOTSCANOUTQ2
    4: HOTSCANRPLYQ
    5: MQ_BACKOUTQ1

PIP:
  REPO:
    URL: 192.168.163.201 

SQUID:
  USER: hotscan
  PASSWORD: banana12
  IP_RANGE: 192.168.163.0

YUM_LOCAL_REPO:
  CONFIG:
    BASEURL: ftp://192.168.163.201/pub

NETWORK:
  IP_RANGE: 192.168.163
  IP_ADDR:
  GATEWAY: 192.168.163.1
  DNS1: 192.168.163.1
  NETMASK: 255.255.255.0
  HOSTNAME:
  INTERFACE: em1
  CONFIG:
    PATH: /etc/sysconfig/network-scripts/ifcfg-em1
